// Code generated by go-swagger; DO NOT EDIT.

package post_customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostCustomerCreatedCode is the HTTP code returned for type PostCustomerCreated
const PostCustomerCreatedCode int = 201

/*PostCustomerCreated Customer created

swagger:response postCustomerCreated
*/
type PostCustomerCreated struct {
}

// NewPostCustomerCreated creates PostCustomerCreated with default headers values
func NewPostCustomerCreated() *PostCustomerCreated {

	return &PostCustomerCreated{}
}

// WriteResponse to the client
func (o *PostCustomerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostCustomerInternalServerErrorCode is the HTTP code returned for type PostCustomerInternalServerError
const PostCustomerInternalServerErrorCode int = 500

/*PostCustomerInternalServerError Internal Server Error

swagger:response postCustomerInternalServerError
*/
type PostCustomerInternalServerError struct {
}

// NewPostCustomerInternalServerError creates PostCustomerInternalServerError with default headers values
func NewPostCustomerInternalServerError() *PostCustomerInternalServerError {

	return &PostCustomerInternalServerError{}
}

// WriteResponse to the client
func (o *PostCustomerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
