// Code generated by go-swagger; DO NOT EDIT.

package get_customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/muly/howto/golang/web/swagger/hello-swagger/models"
)

// GetCustomersOKCode is the HTTP code returned for type GetCustomersOK
const GetCustomersOKCode int = 200

/*GetCustomersOK Customer found

swagger:response getCustomersOK
*/
type GetCustomersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Customer `json:"body,omitempty"`
}

// NewGetCustomersOK creates GetCustomersOK with default headers values
func NewGetCustomersOK() *GetCustomersOK {

	return &GetCustomersOK{}
}

// WithPayload adds the payload to the get customers o k response
func (o *GetCustomersOK) WithPayload(payload []*models.Customer) *GetCustomersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customers o k response
func (o *GetCustomersOK) SetPayload(payload []*models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Customer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCustomersNotFoundCode is the HTTP code returned for type GetCustomersNotFound
const GetCustomersNotFoundCode int = 404

/*GetCustomersNotFound Customer not found

swagger:response getCustomersNotFound
*/
type GetCustomersNotFound struct {
}

// NewGetCustomersNotFound creates GetCustomersNotFound with default headers values
func NewGetCustomersNotFound() *GetCustomersNotFound {

	return &GetCustomersNotFound{}
}

// WriteResponse to the client
func (o *GetCustomersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
